language: python
dist: xenial

python:
- '3.5'

before_install:
- pip install -U pelican

script:
- make publish

deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: gh-pages
